apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: skymoore
spec:
  secretName: tls-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: 'skymoore.com'
  dnsNames:
  - 'skymoore.com'
