apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-ghost-data
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: ghost-gcs
  claimRef:
    namespace: skymoore-com
    name: gcs-ghost-data
  mountOptions:
    - implicit-dirs
    - uid=1000
    - gid=1000
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: skydive-ghost # gcs bucket name
    readOnly: false
