apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-ghost-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: gcs-ghost-data
  storageClassName: ghost-gcs
