---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost-ingress
  namespace: ghost
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - skymoore.com
      secretName: tls-cert
  rules:
    - host: "skymoore.com"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ghost-service
              port:
                name: ghost-port
