---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost-ingress
  namespace: ghost
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:

  tls:
    - hosts:
      - skymoore.yrl.ink
      secretName: tls-cert
  rules:
    - host: "skymoore.yrl.ink"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ghost-service
              port:
                name: ghost-port
