apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: skymoore-com

labels:
  - includeSelectors: true
    pairs:
      app: ghost

resources:
  - ../../base
  - certificate.yaml
  - ingress.yaml
  - serviceaccount.yaml
  - secrets.yaml
  - gcs-pv.yaml
  - gcs-pvc.yaml

patches:
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: ghost-secrets
      $patch: delete
  - path: ghost-statefulset.yaml

images:
  - name: ghost-image
    newName: ghost
    newTag: 5-alpine

configMapGenerator:
  - name: ghost-config
    behavior: merge
    envs:
      - "config/ghost.env"