apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-db-volume
  namespace: skymoore-com
  labels:
    volume: ghost-db-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pd-standard
  gcePersistentDisk:
    pdName: pvc-972c91e3-c3da-42c6-b263-768b13e0654a
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-db-claim
  namespace: skymoore-com
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pd-standard
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volume: ghost-db-volume