---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ghost-secrets
spec:
  provider: vault
  secretObjects:
  - secretName: ghost-secrets
    type: Opaque
    data:
      - key: db-pass
        objectName: db-pass
      - key: db-user
        objectName: db-user
      - key: db-name
        objectName: db-name
      - key: mail-user
        objectName: mail-user
      - key: mail-pass
        objectName: mail-pass
        
  parameters:
    roleName: ghost
    vaultAddress: https://vlt.rwx.dev
    vaultKubernetesMountPath: k8s-skydive
    objects: |
      - objectName: db-pass
        secretPath: secrets/data/ghost
        secretKey: db-pass
      - objectName: db-user
        secretPath: secrets/data/ghost
        secretKey: db-user
      - objectName: db-name
        secretPath: secrets/data/ghost
        secretKey: db-name
      - objectName: mail-user
        secretPath: secrets/data/ghost
        secretKey: mail-user
      - objectName: mail-pass
        secretPath: secrets/data/ghost
        secretKey: mail-pass