---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ghost-storage-class
  namespace: ghost
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
