---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ghost-storage-class
  namespace: ghost
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
