---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-db
spec:
  template:
    spec:
      hostname: ghost-db
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: ghost-db-claim
      initContainers:
        - name: volume-dirs-init-cntr
          image: busybox:1.35
          command:
            - "/bin/mkdir"
          args:
            - "-p"
            - "/db/data"
          volumeMounts:
            - name: db-data
              mountPath: "/db"
      containers:
        - name: ghost-db
          image: db-image
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ghost-secrets
                  key: db-pass
                  optional: false
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: ghost-secrets
                  key: db-user
                  optional: false
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ghost-secrets
                  key: db-pass
                  optional: false
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: ghost-secrets
                  key: db-name
                  optional: false
          ports:
            - name: pod-db-port
              containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
              subPath: data