---
apiVersion: v1
kind: Service
metadata:
  name: ghost-db
  labels:
    app: db-service
spec:
  type: ClusterIP
  selector:
    app: ghost-db
  ports:
  - name: db-port
    protocol:  TCP
    port: 3306
    targetPort: pod-db-port