---
apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  labels:
    app: ghost
spec:
  type: NodePort
  selector:
    app: ghost
  ports:
  - name: ghost-port
    protocol:  TCP
    port: 2368
    targetPort: pod-ghost-port