---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-db-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pd-standard
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volume: ghost-db-volume
