---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  template:
    spec:
      hostname: ghost
      volumes:
        - name: ghost-data
          persistentVolumeClaim:
            claimName: ghost-data-claim

      initContainers:
        - name: init-database
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup ghost-db.skymoore-com.svc.cluster.local; do echo waiting for mydb; sleep 2; done"]

      containers:
        - name: ghost
          image: ghost-image
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ghost-config
          env:
            # DATABASE
            - name: database__connection__database
              valueFrom:
                secretKeyRef:
                  name: ghost-secrets
                  key: db-name
                  optional: false
            - name: database__connection__user
              valueFrom:
                secretKeyRef:
                  name: ghost-secrets
                  key: db-user
                  optional: false
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: ghost-secrets
                  key: db-pass
                  optional: false
            # MAILGUN
            - name: mail__options__auth__user
              valueFrom:
                secretKeyRef:
                  name: ghost-secrets
                  key: mail-user
                  optional: false
            - name: mail__options__auth__pass
              valueFrom:
                secretKeyRef:
                  name: ghost-secrets
                  key: mail-pass
                  optional: false

          ports:
            - name: pod-ghost-port
              containerPort: 2368
              protocol: TCP

          volumeMounts:
            - name: ghost-data
              mountPath: /var/lib/ghost/content