apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ghost

resources:
  - namespace.yaml
  - ghost_deployment.yaml
  - ghost_service.yaml

images:
  - name: ghost-image
    newName: ghost
    newTag: 5-alpine

configMapGenerator:
  - name: ghost-config
    envs:
      - "config/ghost.env"

secretGenerator:
  - name: ghost-secrets
    envs:
      - "config/ghost-secrets.env"